# Определение репликационного контроллера для управления контейнером Redis

kind: ReplicationController # Тип объекта, который мы создаем
apiVersion: v1 # Используемая версия API Kubernetes
metadata: # Метаданные объекта
  name: redis-master # Имя репликационного контроллера
  labels: # Метки, присвоенные этому объекту
    app: redis # Метка, указывающая на приложение
    role: master # Метка, указывающая на роль
spec: # Спецификация объекта
  replicas: 1 # Количество реплик контейнера, которыми должен управлять контроллер
  selector: # Селектор, который определяет, какие контейнеры будут управляться контроллером
    app: redis # Селектор по метке app
    role: master # Селектор по метке role
  template: # Шаблон для создания реплики контейнера
    metadata:
      labels:
        app: redis # Метка app для контейнера
        role: master # Метка role для контейнера
    spec:
      containers: # Список контейнеров, которые будут запущены из этого шаблона
      - name: redis-master # Имя контейнера
        image: registry.k8s.io/redis:e2e # Docker-образ, из которого будет запущен контейнер
        ports: # Список портов, которые контейнер будет использовать
        - name: redis-server # Название порта
          containerPort: 6379 # Номер порта, который контейнер будет использовать

