# Описание контроллера репликации для Redis

kind: ReplicationController # Тип объекта, который мы создаем
apiVersion: v1 # Используемая версия API Kubernetes
metadata: # Метаданные объекта
  name: redis-replica # Имя контроллера репликации
  labels: # Метки, присвоенные этому объекту
    app: redis # Метка, указывающая на приложение
    role: replica # Метка, указывающая на роль
spec: # Спецификация объекта
  replicas: 2 # Количество реплик, которые будут созданы
  selector: # Селектор, который определяет, какие контейнеры будут управляться контроллером репликации
    app: redis # Селектор по метке app
    role: replica # Селектор по метке role
  template: # Шаблон для создания новых реплик
    metadata:
      labels:
        app: redis # Метка, указывающая на приложение
        role: replica # Метка, указывающая на роль
    spec:
      containers:
      - name: redis-replica # Имя контейнера
        image: registry.k8s.io/redis-slave:v2 # Docker-образ, используемый для создания контейнера
        ports:
        - name: redis-server # Имя порта, который будет открыт на контейнере
          containerPort: 6379 # Номер порта, который будет открыт на контейнере

