# Определение сервиса для доступа к контейнеру Redis

kind: Service # Тип объекта, который мы создаем
apiVersion: v1 # Используемая версия API Kubernetes
metadata: # Метаданные объекта
  name: redis-master # Имя сервиса
  labels: # Метки, присвоенные этому объекту
    app: redis # Метка, указывающая на приложение
    role: master # Метка, указывающая на роль
spec: # Спецификация объекта
  ports: # Список портов, которые будут открыты на сервисе
  - port: 6379 # Порт, который будет открыт на сервисе
    targetPort: redis-server # Порт, который будет проброшен на контейнер
  selector: # Селектор, который определяет, какие контейнеры будут доступны через этот сервис
    app: redis # Селектор по метке app
    role: master # Селектор по метке role

